### ISSUE TITLE
DoS vulnerability with jackson

### ISSUE THREAD

**Issue by plokhotnyuk** [yakivy/poppet#2]
[Setting `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` to `false`](https://github.com/yakivy/poppet/blob/08cef9f010094ab96e46840a5419ec6d9b0c03ee/jackson/src/poppet/codec/jackson/instances/JacksonCodecInstances.scala#L18) opens [DoS vulnerability](https://github.com/FasterXML/jackson-module-scala/issues/609)

**Comment by yakivy** [comment]
@plokhotnyuk I've reset `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` to default, thanks for pointing that out.
Btw you can easily replace default object mapper with your own:
```
trait MyCodecInstances extends JacksonCodecInstances {
    override implicit val om: ObjectMapper = ...
}
```
