### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by ioleo** [yakivy/poppet#5]
More examples with multiple services and actual transport layer (eg. `org.scalajs.dom.ext.Ajax`) would be useful.
It is unclear to me how request arguments should be transported (I can't send a Map[String, Json], I have to seriallize it to something like Byte array) and retrieved (do we deserialize the map and pass Map[String, Json] to provider?).

**Comment by yakivy** [comment]
Hi @ioleo . You can check the examples folder, all 3 examples have actual transport layer, for instance:
- here is a consumer based on http4s client: https://github.com/yakivy/poppet/blob/master/example/http4s/consumer/src/poppet/example/http4s/consumer/service/UserServiceProvider.scala#L23
- here is a provider based on http4s route: https://github.com/yakivy/poppet/blob/master/example/http4s/provider/src/poppet/example/http4s/provider/api/ProviderApi.scala#L22
- both use `io.circe.Json` under the hood

In your case, `org.scalajs.dom.ext.Ajax` can receive string as a body, so you can easily convert `io.circe.Json` to string with `json.noSpaces` method. Let me know if you have more questions.

**Comment by yakivy** [comment]
@ioleo btw, you can give me your stack (client, server, data) and if it is not covered in examples, I'll create one.
